apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 8080 # Replace with the port used by your Go script
      targetPort: 8080 # Replace with the port used by your Go script
  type: ClusterIP