apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: cognitopoc7
          image: cognitopoc7:1.0
          command: ["/app/app"]
          args: ["us-east-1_9REgrgq7L", "test", "USAA_user_pool_client" , "read", "write"] 